In [65]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
import sklearn
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [66]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
# YOUR CODE HERE!
lendingdf = pd.read_csv('/Users/andrewmskorupa/Desktop/Bootcamp/Module 20 Supervised Learning/Module 20 Challenge/Starter_Code 11/Resources/lending_data.csv')

# Review the DataFrame
# YOUR CODE HERE!
lendingdf.head(10)

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   
5    10100.0          7.438            50600        0.407115                4   
6    10300.0          7.490            51100        0.412916                4   
7     8800.0          6.857            45100        0.334812                3   
8     9300.0          7.096            47400        0.367089                3   
9     9700.0          7.248            48800        0.385246                4   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0  
5                 1       20600            0  
6                 1       21100            0  
7                 0       15100            0  
8                 0       17400            0  
9                 0       18800            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [67]:
# Separate the data into labels and features

# Separate the y variable, the labels
# YOUR CODE HERE!]
y = lendingdf['loan_status'].values.reshape(-1,1)


# Separate the X variable, the features
# YOUR CODE HERE!
X = lendingdf.copy()
X.drop("loan_status",axis=1,inplace=True)



In [68]:
# Review the y variable Series
# YOUR CODE HERE!
y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [69]:
# Review the X variable DataFrame
# YOUR CODE HERE!
X.head(10)

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   
5    10100.0          7.438            50600        0.407115                4   
6    10300.0          7.490            51100        0.412916                4   
7     8800.0          6.857            45100        0.334812                3   
8     9300.0          7.096            47400        0.367089                3   
9     9700.0          7.248            48800        0.385246                4   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000  
5                 1       20600  
6                 1       21100  
7                 0       15100  
8                 0       17400  
9                 0       18800

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [70]:
# Check the balance of our target values
# YOUR CODE HERE!
lendingdf['loan_status'].value_counts()

0    75036
1     2500
Name: loan_status, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [71]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
# YOUR CODE HERE!
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    random_state=1,
                                                    stratify=y)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [72]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
# YOUR CODE HERE!
classifier = LogisticRegression(solver='lbfgs', random_state=1)
classifier
LogisticRegression(random_state=1)

# Fit the model using training data
# YOUR CODE HERE!
classifier.fit(X_train, y_train)
LogisticRegression(random_state=1)

/Users/andrewmskorupa/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [73]:
# Make a prediction using the testing data
# YOUR CODE HERE!
predictions = classifier.predict(X_test)


### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [74]:
# Print the balanced_accuracy score of the model
# YOUR CODE HERE!
balanced_accuracy_score(y_test, predictions)


0.9442676901753825

In [75]:
# Generate a confusion matrix for the model
# YOUR CODE HERE!
confusion_matrix(y_test, predictions)

array([[18679,    80],
       [   67,   558]])

In [76]:
# Print the classification report for the model
# YOUR CODE HERE!
target_names = ["Class Purple", "Class Yellow"]
print(classification_report(y_test, predictions, target_names=target_names))

              precision    recall  f1-score   support

Class Purple       1.00      1.00      1.00     18759
Class Yellow       0.87      0.89      0.88       625

    accuracy                           0.99     19384
   macro avg       0.94      0.94      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** I would say that the model predicts both labels well since it's producing outcomes greater than 0.90.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [77]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
# YOUR CODE HERE!
ROS_model = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
# YOUR CODE HERE!
X_oversampled, Y_oversampled = ROS_model.fit_resample(X_train, y_train)

In [78]:
# Count the distinct values of the resampled labels data
# YOUR CODE HERE!
Y_oversampled.value_counts()



AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [79]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
# YOUR CODE HERE!
classifiertwo = LogisticRegression(solver='lbfgs', random_state=1)
classifiertwo
LogisticRegression(random_state=1)

# Fit the model using the resampled training data
# YOUR CODE HERE!
classifiertwo.fit(X_oversampled, Y_oversampled)
LogisticRegression(random_state=1)

# Make a prediction using the testing data
# YOUR CODE HERE!
predictionstwo = classifiertwo.predict(X_oversampled)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [80]:
# Print the balanced_accuracy score of the model 
# YOUR CODE HERE!
balanced_accuracy_score(Y_oversampled, predictionstwo)

0.994180571103648

In [81]:
# Generate a confusion matrix for the model
# YOUR CODE HERE!
confusion_matrix(Y_oversampled, predictionstwo)

array([[55945,   332],
       [  323, 55954]])

In [82]:
# Print the classification report for the model
# YOUR CODE HERE!
target_names_two = ["Class Purple", "Class Yellow"]
print(classification_report(Y_oversampled, predictionstwo, target_names=target_names_two))

              precision    recall  f1-score   support

Class Purple       0.99      0.99      0.99     56277
Class Yellow       0.99      0.99      0.99     56277

    accuracy                           0.99    112554
   macro avg       0.99      0.99      0.99    112554
weighted avg       0.99      0.99      0.99    112554



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The model predicted it well with 0.99s across the board.